Literaltype as sdktype
flyteorg/flytekit-java pull request #198
Opened 2023-02-27 20:25 UTC by narape

# TL;DR
Use  SdkLiteralType to create SdkType<T> with low overhead.

## Type
 - [ ] Bug Fix
 - [X] Feature
 - [ ] Plugin

## Are all requirements met?

 - [X] Code completed
 - [ ] Smoke tested
 - [X] Unit tests added
 - [X] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Currently the way to create custom `SdkType<T>` in Java is using `JacksonSdkType`. For example

If a developer wants to define a task equivalent to (String str) -> str.toUpperCase() currently he/she needs to write it as

```java
@AutoService(SdkRunnableTask.class)
public class ToUpperCaseTask extends SdkRunnableTask<ToUpperCaseTask.Input, ToUpperCaseTask.Output> {
  public ToUpperCaseTask() {
    super(JacksonSdkType.of(Input.class), JacksonSdkType.of(Output.class));
  }

  @AutoValue
  public abstract static class Input {
    public abstract SdkBindingData<String> in();
  }

  @AutoValue
  public abstract static class Output {
    public abstract SdkBindingData<String> out();

    public static Output create(String out) {
      return new AutoValue_ToUpperCaseTask_Output(out);
    }
  }

  @Override
  public Output run(Input input) {
    return Output.create(SdkBindingDataFactory.of(input.get().toUpperCase()));
  }
}
```
For such trivial task, defining the AutoValues to define the types takes the majority of the lines.

With this PR the developer could write the task this way instead

```java
@AutoService(SdkRunnableTask.class)
public class ToUpperCaseTask extends SdkRunnableTask<SdkBindingData<String>, SdkBindingData<String>> {
  public ToUpperCaseTask() {
    super(SdkTypes.of(SdkLiteralTypes.strings(), "str"), SdkTypes.of(SdkLiteralTypes.strings(), "upr"));
  }

  @Override
  public SdkBindingData<String> run(SdkBindingData<String> input) {
    return input.get().toUpperCase();
  }
}
```

Defining the types for the task now takes one line only and the run is simplified too as no need to create or access AutoValues

## Tracking Issue
_Remove the '*fixes*' keyword if there will be multiple PRs to fix the linked issue_

fixes https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

2023-02-27 20:27 UTC, narape commented on flytekit-java/src/main/java/org/flyte/flytekit/MonoVariableSdkType.java
> +class MonoVariableSdkType<T> extends SdkType<SdkBindingData<T>> {
**Note to reviewers**
This class is package private but if you have a better name please say so

2023-02-27 20:30 UTC, narape commented on flytekit-java/src/test/java/org/flyte/flytekit/SdkNodeNamePolicyTest.java
> +            .limit(10)
This is unrelated to this change but when creating this PR this test failed.
It is because the birth paradox, I reduced the number of samples to reduce the probability to a really small one

2023-02-27 20:31 UTC, narape commented on flytekit-scala_2.13/src/main/scala/org/flyte/flytekitscala/SdkScalaType.scala
> -    def toBindingData(literal: Literal): BindingData = {
This piece of code was already unused before the changes of this PR

2023-02-27 20:31 UTC, narape commented on flytekit-scala_2.13/src/main/scala/org/flyte/flytekitscala/SdkScalaType.scala
> +  /** Returns a [[SdkType]] for [[Unit]] which contains no properties.
We missed this comment as well in a previous PR

2023-02-28 08:55 UTC, andresgomezfrr commented
@narape How this new type of definition looks with the strongly types? Could you show an example of usage in a workflow?

2023-02-28 08:56 UTC, andresgomezfrr reviewed
@narape How this new type of definition looks with the strongly types? Could you show an example of usage in a workflow?

2023-02-28 10:59 UTC, narape commented
@andresgomezfrr I guess your question comes from passing the name of the property as string, but take a look at the SumTask and now with the latest commit to the FibbonacciWorkflow. 
For example
```scala
    val fib2: SdkBindingData[Long] = builder
      .apply("fib-2", new SumTask(), SumTaskInput(input.fib0, input.fib1))
      .getOutputs
```
notice now `getOutputs` return the `SdkBindingData[Long]` directly, no need to call any `.c()` method. This is why the name of the variable could be defined as string, because it would be hidden from the wiring code, yet still present internally in the promises of the idl

2023-02-28 13:21 UTC, bergman approved these changes
This seems to change very little in the API (only adds a few things), breaks nothing and gives a nicer experience for the single-value input/output 👍

2023-02-28 13:21 UTC, bergman commented on flytekit-java/src/main/java/org/flyte/flytekit/MonoVariableSdkType.java
> +class MonoVariableSdkType<T> extends SdkType<SdkBindingData<T>> {
I think the [arity](https://en.wikipedia.org/wiki/Arity) concept matches this quite well, so `nullary` (0), `unary` (1), `binary` (2), …, `variadic`(n) are the common prefixes for those.
```suggestion
class UnaryVariableSdkType<T> extends SdkType<SdkBindingData<T>> {
```

2023-02-28 13:22 UTC, rafaelraposospot requested changes

2023-02-28 13:22 UTC, rafaelraposospot commented on flytekit-java/src/main/java/org/flyte/flytekit/MonoVariableSdkType.java
> +class MonoVariableSdkType<T> extends SdkType<SdkBindingData<T>> {
I would recommend to change the `Mono...` it's correct in Spanish/Portuguese but it's not a thing in the English languaage. Maybe switch to `Single`

2023-02-28 13:23 UTC, narape commented on flytekit-java/src/main/java/org/flyte/flytekit/MonoVariableSdkType.java
> +class MonoVariableSdkType<T> extends SdkType<SdkBindingData<T>> {
Right, I will follow Jocke advice in the name

2023-02-28 13:23 UTC, bergman commented
> @andresgomezfrr I guess your question comes from passing the name of the property as string, but take a look at the SumTask and now with the latest commit to the FibbonacciWorkflow. For example
> 
> ```scala
>     val fib2: SdkBindingData[Long] = builder
>       .apply("fib-2", new SumTask(), SumTaskInput(input.fib0, input.fib1))
>       .getOutputs
> ```
> 
> notice now `getOutputs` return the `SdkBindingData[Long]` directly, no need to call any `.c()` method. This is why the name of the variable could be defined as string, because it would be hidden from the wiring code, yet still present internally in the promises of the idl

I think this is a little confusing, the method is named `getOutputs` but it returns a single value. This is why I wasn't so keen on naming that method that in the first place 😂

2023-02-28 13:34 UTC, pablocasares approved these changes

2023-02-28 13:37 UTC, rafaelraposospot approved these changes

2023-02-28 13:58 UTC, merged