Added github workflow
flyteorg/flytekit-java pull request #22
Opened 2021-06-04 15:50 UTC by evalsocket

- Added GitHub workflow for the pull request. It will run the build, lint and unit test 
- Added Github workflow for release. it will run build, lint, and unit test. It also publishes jflyte docker image and publish jar package on sonatype

2021-06-05 12:22 UTC, evalsocket commented
@EngHabu Is there a way to verify the workflow before the merge? Release workflow is not tested.

2021-06-07 08:27 UTC, kanterov requested changes
I think we need to iterate on release part. We can look at how it's done in other OSS projects using Maven, and follow the same approach. A good example can be Netty. Except for this, I think we miss a couple more pieces:
- testing for pull requests (only main branch has action)
- publishing of snapshots jars and Docker images (should be done for each build of the main branch)

A good start can be handling the release of jars and Docker images in a separate pull request. And limit the scope of the initial pull request to running `mvn verify` on PRs and main branch builds.

2021-06-07 08:27 UTC, kanterov commented on .github/workflows/release.yaml
> +        filename: ./flytekit-api/target/flytekit-api-${{ steps.bump.outputs.version }}.jar
I'm not sure it's going to work. Maven is going to use a version from the pom file. It will be great if we followed a similar process as for instance in Netty. Here is their CI release setup:

https://github.com/netty/netty/blob/4.1/.github/workflows/ci-release.yml

In this case a bot will bump the version:

https://github.com/netty/netty/commit/9e06241ddbe4d3aedc7994d37450013de276f062

With that, we also don't need custom GitHub actions and can use Maven.

2021-06-07 08:27 UTC, kanterov commented on .github/workflows/release.yaml
> +    runs-on: ubuntu-latest
Should we add a condition to make sure it doesn't run outside of main repo? E.g.
```
if: github.repository == 'flyteorg/flytekit-java'
```

2021-06-07 08:50 UTC, evalsocket commented on .github/workflows/build.yaml
> +name: Flytekit Java Build
ok

2021-06-11 10:58 UTC, evalsocket commented on .github/workflows/build.yaml
> +      run: mvn package
ok

2021-06-11 13:30 UTC, evalsocket commented on .github/workflows/release.yaml
> +    runs-on: ubuntu-latest
No, it is not required for release because we are using a release trigger.

2021-06-14 11:49 UTC, kanterov commented on .github/workflows/build.yaml
> +          SNAPSHOTS_REPOSITORY_URL: "https://s01.oss.sonatype.org/"
I think it should be `https://s01.oss.sonatype.org/content/repositories/snapshots`

2021-06-14 11:49 UTC, kanterov commented on .github/workflows/build.yaml
> +          RELEASE_REPOSITORY_URL: "https://s01.oss.sonatype.org/"
I think it should be `https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/`

2021-06-14 11:56 UTC, kanterov requested changes
I'm not sure 'flytekit-java release" works as intended. In one of the comments before, I mentioned that we should do something close to how Netty does releases. In Netty, the GitHub bot will push commit to change the version in pom.xml. And then perform release against this commit. This is how maven-release-plugin works for instance.

This takes more time to implement. What if we start with publishing only snapshots, and remove this code for now?

2021-06-14 11:56 UTC, kanterov commented on .github/workflows/build.yaml
> +#      - name: Log in to Docker Hub
Why is this commented out?

2021-06-14 11:56 UTC, kanterov commented on .github/workflows/build.yaml
> +        run: mvn deploy -DpreparationGoals=clean -DskipTests=true -Dghcr.io/flyteorg/jflyte  -Ddockerfile.push
Should it be `-Ddocker.image=gcr.io/flyteorg/jflyte`? Probably we can name image as flytekit-java to make it less confusing as well.

2021-06-14 12:15 UTC, evalsocket commented on .github/workflows/build.yaml
> +#      - name: Log in to Docker Hub
It's failing...I think we don't have secrets in place for docker. Can you check ?

2021-06-14 12:15 UTC, evalsocket commented
I removed the release workflow. And only enable build and push workflow for master

2021-06-14 14:25 UTC, kanterov commented
@evalsocket should "Log in to Docker Hub" be done only for the main branch build, similar to how "Release snapshot with Maven" works?

2021-06-14 14:47 UTC, kanterov approved these changes
Nice! Thanks

2021-06-14 14:48 UTC, merged