Added automation for flyteidl proto
flyteorg/flytekit-java pull request #33
Opened 2021-08-30 07:40 UTC by rajatk-31

# TL;DR
- Added a new make target `update_flyteidl` .
- Added a shell script for bump new flyteidl proto.
- Added new Github workflow for automation

## Type
 - [ ] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 _How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
_Remove the '*fixes*' keyword if there will be multiple PRs to fix the linked issue_

fixes https://github.com/flyteorg/flyte/issues/1384

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/1384_

2021-08-30 09:51 UTC, evalsocket commented on scripts/update_flyteidl.sh
> +mv ${OUT}/protos/flyteidl/service/*  jflyte/src/main/proto/flyteidl/service/
It would be great if we can use a loop for running `mv` command. Use an array to declare all the services

2021-08-30 12:50 UTC, evalsocket commented on .github/workflows/flyteidl-automation.yml
> +on:
Is it tested ?

2021-08-30 12:59 UTC, rajatk-31 commented on .github/workflows/flyteidl-automation.yml
> +on:
Yes.
Workflow URL: https://github.com/rajatk-31/flytekit-java/runs/3461746397?check_suite_focus=true

2021-08-30 12:59 UTC, rajatk-31 commented on .github/workflows/flyteidl-automation.yml
> +on:
PR: https://github.com/rajatk-31/flytekit-java/pull/1

2021-08-30 13:12 UTC, evalsocket approved these changes

2021-08-31 07:32 UTC, ckiosidis commented on .github/workflows/flyteidl-automation.yml
> +    name: Update flyteidl
the job is called `update-boilerplate` but the name is `Update flyteidl`
Also in other places it's called boilerplate, should we keep the same naming convention? https://github.com/flyteorg/flyteconsole/blob/master/.github/workflows/boilerplate-automation.yml

2021-08-31 07:35 UTC, ckiosidis commented on .github/workflows/flyteidl-automation.yml
> +    name: Update flyteidl
ah now i see that they are doing different things.
in the other projects flyteidls are not shared in the same way.

2021-08-31 07:37 UTC, ckiosidis commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
I couldnt find the original file that is mentioned here, could you please add a link?

2021-08-31 07:39 UTC, rajatk-31 commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
Yes , here is the link : https://github.com/rajatk-31/flytekit-java/blob/master/scripts/update_flyteidl.sh

2021-08-31 07:42 UTC, ckiosidis commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
Thanks, I actually meant a link towards the boilerplate repo. The warning suggests that the file exists there. Does it?

2021-08-31 09:00 UTC, rajatk-31 commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
https://github.com/rajatk-31/flytekit-java/blob/master/boilerplate/update.sh

2021-08-31 09:55 UTC, ckiosidis commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
should this be included in https://github.com/flyteorg/boilerplate/ ?

2021-08-31 12:17 UTC, evalsocket commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
I think no, It's very specific to flytekit-java

2021-08-31 12:18 UTC, evalsocket commented on scripts/update_flyteidl.sh
> +# TO OPT OUT OF UPDATES, SEE https://github.com/flyteorg/boilerplate/blob/master/Readme.rst
@rajatk-31 Please remove the boilerplate comment from script

2021-08-31 12:21 UTC, evalsocket commented on .github/workflows/flyteidl-automation.yml
> +    name: Update flyteidl
for now, let's copy the flyteidl and you will take care of the generatation part...In meanwhile I will release the maven package in flyteidl. It would be great if they are available in maven

After this, you can decide what to do next in flytekit-java

2021-09-02 10:18 UTC, ckiosidis approved these changes

2021-09-02 13:35 UTC, narape requested changes

2021-09-02 13:35 UTC, narape commented on scripts/update_flyteidl.sh
> +#copying latest proto from flyteidl to flytekit-java
@evalsocket this file needs execution permission for the make to work

2021-09-15 07:12 UTC, evalsocket commented on scripts/update_flyteidl.sh
> +#copying latest proto from flyteidl to flytekit-java
yes....@rajatk-31 did you added the right permission to `update_flyteidl.sh`

2021-09-21 17:11 UTC, closed without merging