WIP Add Container task
flyteorg/flytekit-java pull request #99
Opened 2022-05-23 11:43 UTC by evdokim

Adds support for ContainerTask: https://docs.flyte.org/projects/flytekit/en/latest/generated/flytekit.ContainerTask.html

Container tasks will allow to execute arbitrary container as Flyte task

## _Read then delete this section_

_- Make sure to use a concise title for the pull-request._

_- Use #patch, #minor or #major in the pull-request title to bump the corresponding version. Otherwise, the patch version
will be bumped. [More details](https://github.com/marketplace/actions/github-tag-bump)_

# TL;DR
_Please replace this text with a description of what this PR accomplishes._

## Type
 - [ ] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 _How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
_Remove the '*fixes*' keyword if there will be multiple PRs to fix the linked issue_

fixes https://github.com/flyteorg/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/flyteorg/flyte/issues/<number>_

2022-06-09 07:38 UTC, evdokim commented on flytekit-java/src/main/java/org/flyte/flytekit/SdkRunnableTaskRegistrar.java
> -      SdkResources sdkResources = sdkTask.getResources();
moved to `SdkResources.java`

2022-06-23 15:09 UTC, narape requested changes
@evdokim first, thanks for the contribution. Here is one bug and some minor changes

2022-06-24 08:46 UTC, evdokim commented on flytekit-api/src/main/java/org/flyte/api/v1/ContainerTask.java
> +    return "raw-container".toLowerCase(Locale.ROOT);
Good catch, I don't even remember why I added this conversion

2022-06-24 08:48 UTC, evdokim commented on flytekit-java/src/main/java/org/flyte/flytekit/SdkResources.java
> +  public Resources toResources() {
Agree, `toIdl()` looks more cleaner

2022-06-24 09:30 UTC, evdokim commented
@narape thank you for the review, I addressed your comments, could you take a look again?

2022-06-24 14:35 UTC, narape approved these changes

2022-06-24 14:38 UTC, narape commented
Snyk problem was fixed in https://github.com/flyteorg/flytekit-java/pull/113

2022-06-24 14:38 UTC, merged